"""Schema creation for local mode (SQLite) — straight from models, no Alembic.

`create_all` only ever adds missing *tables*, so a database created by an
earlier release kept its old columns and every query naming a new one failed
with ``no such column`` — the release notes said nothing, and the dashboard
answered 500. Local mode now also adds columns that the models grew.

ponytail: additive only. A column that was dropped, renamed or retyped still
needs a real migration; this covers the case local mode actually hits, which is
a release adding a nullable-or-defaulted column.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from sqlalchemy import inspect, text
from sqlalchemy.schema import CreateColumn

import suitest_db.models  # noqa: F401  # side-effect: register every model on Base.metadata
from suitest_db.base import Base

if TYPE_CHECKING:
    from sqlalchemy.engine import Connection
    from sqlalchemy.ext.asyncio import AsyncEngine


async def create_local_schema(engine: AsyncEngine) -> None:
    """Create the local schema, and add any columns the models have grown."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
        await conn.run_sync(_add_missing_columns)
        await conn.run_sync(_drop_legacy_columns)


def _add_missing_columns(conn: Connection) -> None:
    """``ALTER TABLE ... ADD COLUMN`` for model columns the database lacks.

    The column spec is rendered by SQLAlchemy's own `CreateColumn`, so a NOT
    NULL column with a server default arrives exactly as the model declares it. A NOT NULL column
    *without* a default cannot be added to a table that already has rows, so it
    is skipped rather than crashing startup: adding one is a real migration.
    """
    inspector = inspect(conn)
    existing_tables = set(inspector.get_table_names())
    # Not `sorted_tables`: ALTER order is irrelevant here, and sorting warns
    # about the projects/suites FK cycle for nothing.
    for table in Base.metadata.tables.values():
        if table.name not in existing_tables:
            continue
        present = {column["name"] for column in inspector.get_columns(table.name)}
        for column in table.columns:
            if column.name in present:
                continue
            if not column.nullable and column.server_default is None:
                continue
            spec = CreateColumn(column).compile(dialect=conn.dialect)
            conn.execute(text(f"ALTER TABLE {table.name} ADD COLUMN {spec}"))


def _drop_column_and_index(
    conn: Connection,
    table_name: str,
    column_name: str,
    index_name: str | None = None,
) -> None:
    """Safely drop a column and its optional index from an SQLite table if present."""
    import contextlib

    inspector = inspect(conn)
    if table_name not in set(inspector.get_table_names()):
        return
    existing_cols = {c["name"] for c in inspector.get_columns(table_name)}
    if column_name not in existing_cols:
        return
    if index_name:
        with contextlib.suppress(Exception):
            conn.execute(text(f"DROP INDEX IF EXISTS {index_name}"))
    with contextlib.suppress(Exception):
        conn.execute(text(f"ALTER TABLE {table_name} DROP COLUMN {column_name}"))


def _drop_legacy_columns(conn: Connection) -> None:
    """Drop legacy columns and indexes that were removed in newer releases.

    SQLite 3.35.0+ supports ``ALTER TABLE ... DROP COLUMN``. In local mode
    without Alembic, this ensures upgraded databases do not retain deprecated
    NOT NULL columns (such as the legacy capability tiers removed in 0051)
    which break INSERT statements generated by newer models.
    """
    _drop_column_and_index(conn, "runs", "tier_at_runtime", "ix_runs_tier")
    _drop_column_and_index(conn, "workspace_capabilities", "tier", "ix_workspace_capabilities_tier")
    _drop_column_and_index(conn, "workspaces", "strict_zero_validation")
    _drop_column_and_index(conn, "document_chunks", "embedding")


def _main() -> None:
    """CLI: create the local schema at ``SUITEST_DATABASE_URL``. Idempotent."""
    import asyncio
    import os

    from sqlalchemy.ext.asyncio import create_async_engine

    url = os.environ.get("SUITEST_DATABASE_URL")
    if not url:
        raise SystemExit("SUITEST_DATABASE_URL is not set")

    async def _run() -> None:
        engine = create_async_engine(url)
        try:
            await create_local_schema(engine)
        finally:
            await engine.dispose()

    asyncio.run(_run())


if __name__ == "__main__":
    _main()
